### PR TITLE
Review analysis of Wallowing-in-Despair

### PR DESCRIPTION
**Pull request by chexxor**
I started to change the analysis from a summary-style to a "A believes B to be true" format. I think the latter is a better form for an analysis result because it is more consumable and qualifies the fact with the role of the person who believed the fact.

### CODE REVIEW

**Comment by chexxor** [comment]
I'm interested to hear your response to my review of your analysis, @JordanMartinez. No hurry, of course. I made a bit of a change to the analysis style you were using, so I'd like to know your view of it.

**Comment by chexxor** [comment]
In the template in the ReadMe file in the sources directory, it prescribes the format:

> > Relevant info stated in that comment
> 
> my interpretation of that info

The format of the "my interpretation of that info" isn't prescribed or explained, however. I can update that part of the ReadMe when I hear back from you and if we decide to clarify that part.

**Comment by chexxor** [comment]
Oh, I see that "interpretation" was given a definition in the ReadMe.

> Once assessed, one interprets the main themes/ideas that one hears the source communicating.

It's unclear what a "main theme/idea" is, so I was unable to pull those out of the source. More importantly, it's not clear to me the how a "main theme/idea" is valuable as an interpretation of a source. I'm more familiar with statements of belief & parsing a statement of belief from another person, and I feel like personal statements of belief are a universally-acceptable statement of fact. Whether that person's belief is true or not is up for interpretation.

Is this analysis/interpretation phase intended to be evaluating the correctness/truthfulness of another person's beliefs? Or simply logging the concise belief another person has?

**Comment by JordanMartinez** [comment]
> I'm more familiar with statements of belief & parsing a statement of belief from another person, and I feel like personal statements of belief are a universally-acceptable statement of fact. Whether that person's belief is true or not is up for interpretation.

That was my goal as well in how I phrased such 'interpretations,' but I don't think I always did that. Sometimes, my interpretation was literally 'my' interpretation and evaluation of whether some statement was true now that we are farther ahead in time than they were at that time.

> It's unclear what a "main theme/idea" is, so I was unable to pull those out of the source. More importantly, it's not clear to me the how a "main theme/idea" is valuable as an interpretation of a source.

That's what I meant by 'main theme/idea:' the main thing that the person is communicating. I don't think all of these 'main ideas' are valuable in creating the Context/Narrative, but I thought it would be thorough to summarize all of the ones I found.
Summarizing sources' main ideas that don't necessarily fall inside of the documentation scope of things is likely my researchy/curiosity coming out more than anything

I'll start reviewing this PR.

**Comment by JordanMartinez** [comment]
Yeah, this format looks much better.

**Comment by chexxor** [comment]
Ok, I'll continue reviewing & revising tomorrow. 👍 Thanks for the review!

**Pull request merged**
