### PR TITLE
Create Index for Sources

### PR DESCRIPTION
**Pull request by chexxor**
Here's what I was thinking for the list of sources. I'll update the workflow document in this branch, too.
Fixes https://github.com/chexxor/purescript-documentation-discussion/issues/24

I would find this useful to see if you already considered a source that I newly discovered and wanted to add to this project.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Ok. Looks good to me. Could you also include the date of the source (ss we discussed in other comments)?

**Comment by JordanMartinez** [comment]
I think this file should also include the 'type' of some source

**Comment by chexxor** [comment]
I added the date and type of source as columns. I'd like to merge this as-is, just to avoid needing to make this one file perfect all-at-once. I think it's easy to make improvements/additions line-by-line over time.

**Comment by JordanMartinez** [comment]
Sounds good to me. One other change we could make is to sort the sources chronologically.

**Comment by JordanMartinez** [comment]
LGTM. See also #36

**Pull request merged**
