### PR TITLE
Add last item from MVI_Architecture

### PR DESCRIPTION
**Pull request by chexxor**

### CODE REVIEW

**Comment by JordanMartinez** [comment]
You deleted the MVI file? Shouldn't we keep that so people can refer back to it for context?

Looks good otherwise.

**Comment by chexxor** [comment]
I noticed that all the other documents were removed from that file, so I just followed suit by deleting it.

@JordanMartinez I agree it might be helpful to be able to refer back to the documents. Should I make an issue/work item to bring them back? I think there are more missing. I can comb through the git history to bring them back relatively easily, I think.

**Comment by JordanMartinez** [comment]
I moved them into the 'copied' folder. That's why they are no longer there. Could you do the same? Then we can merge this.

**Comment by chexxor** [comment]
Yeah, I wasn't sure what that Copied folder was for, I thought you had other intentions for its contents. I'll go back and revert the files I deleted and add them to this PR. 👌  Sorry about that miscommunication!

**Comment by JordanMartinez** [comment]
I forgive you. I could probably have communicated that better.

**Comment by chexxor** [comment]
@JordanMartinez I brought back that file. I checked the Index.md file and the git history to verify that there aren't any other source files I didn't accidentally delete - looks like this was the only one. 👍

**Comment by JordanMartinez** [comment]
Ok. Then let's get this merged.

**Pull request merged**
