### PR TITLE
Adopt Jordan's suggested document structure

### PR DESCRIPTION
**Pull request by chexxor**
https://github.com/chexxor/purescript-documentation-discussion/pull/50#discussion_r271113368

### CODE REVIEW

**Comment by chexxor** [comment]
@JordanMartinez  Based on past discussion about changing priorities and such, I don't expect you to review this, but I'll likely wait anyways and re-review it myself in a bit.

**Comment by JordanMartinez** [comment]
I looked this over and found a number of issues:
- header names that don't explain the flow of thought as well as they could or emphasize the wrong point/idea
- most of the content that I wrote was deleted rather than moved into a new file and linked to that file
- the `git diff` is horrendous (not your fault) so it makes reviewing this PR very difficult.

I think I might be better for me to do this.

**Comment by chexxor** [comment]
Oh right, I moved the deleted content into a text file, and I intended to move that into a separate file to link to. Sorry about that! I can finish doing that!

**Comment by JordanMartinez** [comment]
I'm almost done myself with a PR

**Comment by chexxor** [comment]
I'll close this one in favor of yours, https://github.com/chexxor/purescript-documentation-discussion/pull/66

**Pull request closed without merging**
