### PR TITLE
Change license to that used by PS documentation project

### PR DESCRIPTION
**Pull request by chexxor**
Change the license to that used in the PureScript/documentation project.

As discussed in https://github.com/chexxor/purescript-documentation-discussion/issues/23

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Minor tidbit, but I should probably be included in that copyright, too.

Also, this version of the license does not require attribution to us for our work. Both licenses we proposed were BY-NC-SA whereas this is only NC-SA

**Comment by chexxor** [comment]
No, the "Creative Commons Attribution-NonCommercial-ShareAlike" license is the "BY-NC-SA" license, the same as used in the PS documentation project.

Also, I added a CONTRIBUTORS file. I'm not sure how the LICENSE and CONTRIBUTORS file relate. Can we just delete the LICENSE file? That's what the purescript/documentation project did. Well, it gets rid of the idea that the license was one person's, because it only had my name on it. I can finally understand why the purescript-documentation project did it like this -- the license is still technically there, but the file name is different and it's easier to read in how it lists all people who own the license.

**Comment by JordanMartinez** [comment]
> No, the "Creative Commons Attribution-NonCommercial-ShareAlike" license is the "BY-NC-SA" license, the same as used in the PS documentation project.

I initially said that because I saw [this line](https://github.com/chexxor/purescript-documentation-discussion/pull/35/commits/299777521e73d601a61335d96bc66858d24548b7#diff-9879d6db96fd29134fc802214163b95aR4). However, [this line](https://github.com/chexxor/purescript-documentation-discussion/pull/35/commits/299777521e73d601a61335d96bc66858d24548b7#diff-9879d6db96fd29134fc802214163b95aR9) linked to the correct license.
Regardless, the current state of this PR is correct in the license in both situations.

I don't have a problem with deleting the LICENSE file, but we should include a note on the ReadMe stating that one should look at the CONTRIBUTORS file to see the license.

**Comment by chexxor** [comment]
@JordanMartinez I think we can close this issue if you add your name to the CONTRIBUTORS.md file.

**Pull request merged**
